### ISSUE TITLE
Split the components code from the example app code

### ISSUE THREAD

**Issue by severo** [source-cooperative/components#3]
It would be clearer to have two directories, one for the components code (the lib, that will be included in the npm package) and one for the demo app.

<strike>The lib does not require Next.js for example, so: we should not require it in the package.json file.</strike> Edit: the components depend on Next functions (link, router), so: yes, we require Next.js

<strike>By the way, Next.js shouldn't even be used, since the demo app is purely frontend. So, maybe replace it with Vite, or have two example apps: one with Next, the other with Vite.</strike> -> we now build a static app with Next.js.

Proposed structure: a monorepo with:
- packages/components: the library
- apps/demo: the demo app

<strike>The demo app should consume the published package (https://www.npmjs.com/package/@source-cooperative/components) to showcase how to use it. We don't want to rely on internal tsx files, but on build JS files + type definitions.</strike> Not sure, after all. The app is mainly for internal use, to be able to use the same components in the source and the viewers apps.

**Comment by severo** [comment]
wdyt @jedsundwall.

I think we should do the same in https://github.com/source-cooperative/viewers.source.coop/.

**Comment by jedsundwall** [comment]
Agree! I trust your judgment on this.

**Comment by severo** [comment]
OK! I'll work on it

**Comment by severo** [comment]
Let's close for now, as it's not super urgent. The package works (we use it in viewers.source.cooperative), so... we might improve things later if needed (ie: remove pages/ from the bundled types for example), but not crucial.
